# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HuL3iPX3VISQpvOD8XROw_LrB9WNkH6Q
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import truncnorm

def simulate_cloudiness_mc(mu, sigma, lower, upper, n_trials=10000):

    # Convert bounds for truncated normal
    a = (lower - mu) / sigma
    b = (upper - mu) / sigma

    samples = truncnorm.rvs(a, b, loc=mu, scale=sigma, size=n_trials)

    return samples

def generate_cloudiness_analysis(mu, sigma, lower, upper, data):

    fig, ax = plt.subplots(figsize=(10,6))

    ax.hist(data, bins=50, density=True,
            alpha=0.6,
            color='#76d7c4',
            edgecolor='white',
            label='Empirical Distribution (MC)')

    x = np.linspace(lower, upper, 1000)

    a = (lower - mu) / sigma
    b = (upper - mu) / sigma
    pdf = truncnorm.pdf(x, a, b, loc=mu, scale=sigma)

    ax.plot(x, pdf, color='#1b4f72', lw=2.5,
            label='Analytical Truncated Normal PDF')

    ax.axvline(lower, linestyle='--', color='black')
    ax.axvline(upper, linestyle='--', color='black')

    ax.set_title("Monte Carlo Verification for Cloudiness (Bounded [0,1])")
    ax.set_xlabel("Cloudiness Fraction")
    ax.set_ylabel("Probability Density")
    ax.legend()
    ax.grid(True, linestyle=':')

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":

    MU = 0.5
    SIGMA = 0.2
    LOWER = 0
    UPPER = 1

    cloud_data = simulate_cloudiness_mc(MU, SIGMA, LOWER, UPPER)

    generate_cloudiness_analysis(MU, SIGMA, LOWER, UPPER, cloud_data)