# -*- coding: utf-8 -*-
"""Monte Carlo Ice Albedo Validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sd961tQChboFJf3jHtelgyzIz1XbS2vB
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import truncnorm

# 1. PARAMETERS (Based on Machguth 2008 & Box 2012)
# ---------------------------------------------------------
np.random.seed(42)  # For reproducibility
N = 100000          # 100,000 Monte Carlo iterations

mu_alb = 0.34       # Mean albedo (Average reflectivity)
sigma_alb = 0.05    # Standard deviation (Uncertainty)
low = 0.2           # Lower physical bound (Dirty ice)
high = 0.6          # Upper physical bound (Clean ice)

# 2. MONTE CARLO SIMULATION
# ---------------------------------------------------------
# Define the bounds in terms of standard deviations for truncnorm function
a = (low - mu_alb) / sigma_alb
b = (high - mu_alb) / sigma_alb

# Generate 100,000 random samples (The Monte Carlo Simulation)
albedo_samples = truncnorm.rvs(a, b, loc=mu_alb, scale=sigma_alb, size=N)

# 3. THEORETICAL PDF (The Line Graph)
# ---------------------------------------------------------
# Create an x-axis range to draw the smooth theoretical curve
x = np.linspace(0.15, 0.65, 1000)
theoretical_line = truncnorm.pdf(x, a, b, loc=mu_alb, scale=sigma_alb)

# 4. PLOTTING THE OVERLAP
# ---------------------------------------------------------
plt.figure(figsize=(12, 7))

# Plot the Monte Carlo results as a histogram (Simulated)
plt.hist(albedo_samples, bins=100, density=True, color='skyblue',
         alpha=0.6, edgecolor='white', label='Monte Carlo Simulation (100k samples)')

# Plot the Theoretical PDF line (The mathematical theory)
plt.plot(x, theoretical_line, color='darkblue', linewidth=3,
         label='Theoretical Truncated Normal PDF')

# Add Mean marker and styling for the report
plt.axvline(mu_alb, color='red', linestyle='--', label=f'Mean (μ): {mu_alb}')
plt.title('Validation of Ice Albedo Model: Monte Carlo vs. Theoretical PDF', fontsize=14)
plt.xlabel('Ice Albedo ($\\alpha$)', fontsize=12)
plt.ylabel('Probability Density', fontsize=12)
plt.xlim(0.15, 0.65)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend()

plt.tight_layout()
plt.show()

# Print statistical verification
print(f"--- Simulation Verification ---")
print(f"Simulated Mean: {np.mean(albedo_samples):.4f}")
print(f"Theoretical Mean: {mu_alb}")